language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: A5YDe7lTSVswnc0Xu6cfeQLleRwRpy2F7LkdpRgo/t913ov5vGSM9w7qpdlCP698sld5CyBdpEwN54WWP9EQ6cxouf8BBRR8RBmeMb/tEKiX5DZwozEwWYRk19U65eC4XA4T9+HdBSCNaApHY6PxZreULmt53v7GsjoHps85kVIWBHVrt0VWW6inBsKbMNHEHET5e5n+Zu2NyCINrT1HoS8DRiJH3SXsakpjijJDb5iietV+wtI65pla5eEmoJC8lEHmOmLxNOX3eRtq9prmlol6VAzfGTyB6QyQk0pnh5DU9g0JOXDHb/JZXu8nYoLAHZu39oLx0CZ8R7/sswQoxMfvaZKGsAA15NtqyzpL0xj2ekd5ZehGXqn1xz+3Obu7FLwgyx556smG2K5zFy35bsIEgAAcfnu5u4PbwK5OkkOJVCunIDIacVxLy1PCLLHwOgti0288Fgeg6M2TpZYZBs5rKB4Fjt1UHIDNaz0eVCzbUs6Q3vqxzVYyhN01lzyBv+ZIC/xfkUw1Bqz97x7IdDOQ9gktwM4tO7Y0Ci1tQtJbVCHOypTqsaa8SyyJ0Oazo+LLrwixKWB3E30PiD+3uUYOhka4shuNgaX/dldts3C+kJ06bSeBuWmgtbf5Tv0PD76w76o5dTuzBAcxdcKJzt03CE5CWOSIqcZu0Hp1AhA=
  app: betr-business-server
  on:
    repo: rzavala1989/betr-business-server
